# Generated by Django 5.2.3 on 2025-06-28 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('lightly_active', 'Lightly active (light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very active (hard exercise/sports 6-7 days a week)'), ('extra_active', 'Extra active (very hard exercise/sports & physical job or training twice a day)')], default='sedentary', max_length=20)),
                ('maintanance_cals', models.IntegerField(null=True)),
                ('goal_cals', models.IntegerField(null=True)),
                ('body_fat', models.FloatField(blank=True, null=True)),
                ('carb', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('fibre', models.FloatField(null=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('cuisine', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
