# Generated by Django 5.2.3 on 2025-06-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_carb_userprofile_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='carbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fibre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='protein',
            field=models.IntegerField(null=True),
        ),
    ]
