# Generated by Django 5.2.1 on 2025-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_carbs_alter_userprofile_fats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='maintanance_cals',
            new_name='maintenance_cals',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
