# Generated by Django 5.2.1 on 2025-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_maintanance_cals_userprofile_maintenance_cals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
