# Generated by Django 5.2.1 on 2025-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cuisine',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
