# Generated by Django 5.2.1 on 2025-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
